name: Publish

on:
  workflow_dispatch: 
    inputs:
      update_type:
        description: Major, Minor, or patch
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"

    - name: update version
      id: update-version
      run: |
        cd libs/react-numerics
        echo '::set-output name=VERSION::$(npm version ${{ github.event.inputs.update_type }} -m "Test v%s")'
        cd ../..

    - name: Show version
      run: echo 'Version is ${{ steps.update-version.outputs.VERSION }}'

    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install

    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: typedoc

    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: build

    - run: cat dist/libs/react-numerics/package.json
    - run: echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    - run: cat libs/react-numerics/package.json

    - run: cd dist/libs/react-numerics


