name: Publish

on:
  workflow_dispatch: 
    inputs:
      update_type:
        description: Major, Minor, or patch
        required: true
        default: patch
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"

    - id: Setup-Git
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: update version
      id: update-version
      run: |
        cd libs/react-numerics
        git tag $(npm version ${{ github.event.inputs.update_type }} ) && git add package.json && git commit -m "Bump version"
        cd ../..

    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install

    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: typedoc

    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: build

    - run: cd dist/libs/react-numerics
    
 #   - name: Publish to NPM Registry
 #       uses: JS-DevTools/npm-publish@v1
 #       with:
 #         token: ${{ github.event.inputs.npm_token }}

    - id: Tag-push
      shell: bash
      run: |
        git push
        git push --tags
