name: Publish

on:
  workflow_dispatch: 
    inputs:
      update_type:
        description: Major, Minor, or patch
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  publish:
    runs-on: ubuntu-latest
