name: Publish

on:
  workflow_dispatch: 
    inputs:
      update_type:
        description: Major, Minor, or patch
        required: true
        default: patch
        type: choice
        options:
        - major
        - minor
        - patch
      tag:
        description: Tag, next does not save back to GIT
        required: true
        default: next
        type: choice
        options:
        - latest
        - next
     

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"

    - id: Setup-Git
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: update version
      id: update-version
      run: |
        cd libs/react-numerics
        git tag $(npm version ${{ github.event.inputs.update_type }} ) && git add package.json
        cd -

    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install

    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: typedoc

    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: build

    - run: cd dist/libs/react-numerics

    - id: npm-publish
      name: Publish to NPM Registry
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: ${{ github.event.inputs.tag }}
        dryRun: true

    - id: git-push
      if: ${{ github.event.inputs.tag == 'latest' }}
      shell: bash
      run: |
        git commit -m "Publish version ${{ steps.npm-publish.outputs.version }}"
        git push
        # git push --tags
